name: auto-deployment

on:
  schedule:
    # kst 6:30 am / utc 9:30 pm
    - cron: "30 21 * * *"
    # kst 11:30 am / utc 2:30 am
    - cron: "30 2 * * *"
    # kst 2:30 am / utc 5:30 pm
    - cron : "30 17 * * *"
  # only for test
   workflow_dispatch:
      inputs:
         logLevel:
            description: 'Log level'     
            required: true
            default: 'warning'
         tags:
            description: 'test'
jobs:
  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - uses: actions/cache@v2 
        with:
          path: ${{ github.workspace }}/node_modules
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - run: npm install 
      - run: npm run build
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: gh-pages
          file_pattern: 'out/*'
          commit_message: Automated publish